### ISSUE TITLE
Firmware freezes on "save"

### ISSUE THREAD

**Issue by fnordsh** [gavanfantom/hello-firmware#1] opened 2019-08-23 10:26 UTC
When trying to save a new Text or the settings on the badge, the system freezes and does not react to any input anymore, until I turn it off and on again. The data in question is then lost. I reformatted the filesystem using the `format` command over the serial connection, and that fixed it, but only for a short wihle. Is this likely a firmware issue or rather a defective flash chip?

**Comment by gavanfantom** [comment] 2019-08-24 16:28
It's a firmware issue. You can reproduce it by using the left or right buttons to change media before opening the menu. This is because the previous/next media functions weren't properly closing the currently open file before opening the new one, and then later filesystem operations went into an infinite loop because they were left with a circular reference in a linked list.

I believe this is now fixed.

**Closed as completed by gavanfantom** 2019-08-24 16:28 UTC

**Comment by fnordsh** [comment] 2019-08-24 16:48
Awesome, thanks!
